### ISSUE TITLE
Lux Personal Terrain shader lighting and shadow issues in Unity 5.6.2f1 Personal

### ISSUE THREAD

**Issue by ArtyIF** [larsbertram69/Lux-2.02-Personal#2]
### Problem
The lighting for Lux Personal Terrain shader (Lux/Standard Lighting/Nature/Terrain/Standard) is broken in Unity 5.6.2f1 Personal. To be more precise, terrain recieves no shadows and at some angle the lights stop shading the terrain if base map for it is rendered. GIF showing this bug is below:
![honeycam 2017-07-12 17-26-32](https://user-images.githubusercontent.com/8017858/28131456-97d6b31e-6742-11e7-99ef-d451db9e377e.gif)
### Reproduction
1. Create a scene
2. Add a terrain
3. Assign a terrain material to one with Lux/Standard Lighting/Nature/Terrain/Standard shader
4. Add a spot light
5. Set rotation to (0, 135, 0) (you'll see that spot light is not rendered fully)
6. Add a mesh on a scene (make sure Directional Lights has shadows on) (you'll see the lack of shadows)
7. Set Base Map Dist to 0 (see lighting and shadows are just fine)
### Steps taken to attempt to fix the problem
1. Updated my videocard drivers to latest beta version
2. Rolled back to stable because I expierenced some issues with a beta
3. Made sure the project's configured properly (rendering path is deferred on all tiers, Deferred and Deferred Reflections use custom Lux shader, color space is linear, tier and shader model emulations are off, Unity uses DX11 (it says `<DX11>` in the window title))
### PC Specs
PC: HP Pavilion g6 g6-2211sr (yes, it's an old one (released AFAIR in late 2012), but it handles Unity just fine)
RAM: 4 GB DDR3
Discrete GPU: AMD Radeon HD 7420G
Mobile GPU: AMD Radeon HD 7610M (Device Manager just says "AMD Radeon HD 7600M Series" but AFAIR Radeon Settings shipped with beta drivers said it's 7610M)
APU: AMD A4-4300M
OS: Windows 10 x64 Anniversary Update (build 14393.1358)

**Comment by larsbertram69** [comment]
thanks for your bug report.
unfortunately i have not been able to reproduce your problem.
in fact it might be related to drivers or your gpu – and all i have are nvidia gpus.

sorry about that,
lars

**Comment by ArtyIF** [comment]
ok, that might be my project's issue... gon' test it on another one
also i have a friend that has nvidia gtx 1050, i'll send a build to him

**Comment by ArtyIF** [comment]
yup... seems like my drivers/gpu issue
now making a game build and sending it to my friend
if the problem's still there, i'll reopen the issue
but now will try to fix the shader with my like 1-2% ShaderLab knowledge

**Comment by larsbertram69** [comment]
sounds like a good plan :)

**Comment by ArtyIF** [comment]
woah! i fixed it!
there was no line in firstpass surface shader:
`o.Normal = half3(0,0,1);`
also it fixed reflections

**Comment by dkyeck** [comment]
so – what? i am a bit confused.

**Comment by ArtyIF** [comment]
@dkyeck just add this line after line 99:
`o.Normal = half3(0,0,1);`
in "Standard Terrain FirstPass" shader
