### ISSUE TITLE
Error Please help

### ISSUE THREAD

**Issue by MicaXxX** [larsbertram69/Lux-2.02-Personal#4]
I am having a very strange error while assigning the First pass shader for terrain; in unity **2018.3.8**, all of the errors i have fixed but cant seem to get rid of the following error:

**In short:** Unexpected identifier "Lux". Expected one of: typedef const void inline uniform nointerpolation extern shared static volatile row_major column_major struct or a user-defined type

**Full Context from console:** Shader error in 'Lux/Standard Lighting/Nature/Terrain/Standard': Unexpected identifier "Lux". Expected one of: typedef const void inline uniform nointerpolation extern shared static volatile row_major column_major struct or a user-defined type at .../Lux Core/Lux Features/LuxDynamicWeather.cginc

This error is occuring on all the terrain shaders;

Standard Terrain AddPass / Standard Terrain Base / Standard Terrain FirstPass, but is coming only on the shaders in the Lux custom Standard Shaders.

Can you please help me out if possible to check what might be the reason and possible solution to get this fixed, i have tried almost everything possible under my little knowledge of shaders.

Thanks in advance
Reagrds,

**Comment by larsbertram69** [comment]
hi there,

unity changed the shader compiler during the – i can’t remember x cycle.
so to initialize a custom struct you have to use the hlsl syntax.

attached you will find a new LuxStructs.cginc which should do the trick.

best, lars

**Comment by MicaXxX** [comment]
Sorry but you said there is an attachment .... but i cant seem to find anything attached.

Regards,

**Comment by MicaXxX** [comment]
Thanks it solved all the issues.
