### ISSUE TITLE
RGA texture

### ISSUE THREAD

**Issue by snooze321** [larsbertram69/Lux-2.02-Personal#6]
Hi, I was wondering how you generate the red and green map for the hair? Also known as the Metallic Occlusion Smoothness map?

**Comment by larsbertram69** [comment]
> Hi, I was wondering how you generate the red and green map for the hair? Also known as the Metallic Occlusion Smoothness map?
> 
> 

that is fully up to you...

**Comment by snooze321** [comment]
What I mean is that I've never seen this type of red and green map before and have found no resources online that recognise it let alone about how to create it. I was hoping you could shed some light on its creation.

**Comment by dkyeck** [comment]
the hair shader does not use 2 specular lobes like other hair shading models. so it abuses metalness to allow you to get some colored specular highlights (as from the back faces of the hair fibres). so red is just some random stuff adding a bit more metalness here and there.
green in the example texture is a pretty poor ambient occlusion map...
